import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kumo Africa Admin v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>Kumo Africa Admin v2</p>
    </div>
  );
}
