import { Box, Grid, GridItem, Text } from "@chakra-ui/react";
import {
  DashboardTransactions,
  GetLoans,
  PayWithKumo,
  QuickActions,
  RecentTransactions,
  WalletBalance,
} from "components/Dashboard";
import { navStates, useNavContext } from "context/NavProvider";

import Head from "next/head";
import { useEffect } from "react";

export default function Home() {
  const { setActiveNav } = useNavContext();
  useEffect(() => {
    setActiveNav(navStates?.dashboard);
  }, []);
  return (
    <div>
      <Head>
        <title>Kumo Africa Admin v2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box minH="80vh" px="24px">
        <Grid templateColumns={["repeat(2, 1fr)"]} gap="6">
          <GridItem colSpan={1}>
            <WalletBalance />
            <QuickActions />
            <RecentTransactions />
          </GridItem>
          <GridItem colSpan={1}>
            <DashboardTransactions />
            <PayWithKumo />
          </GridItem>
        </Grid>
      </Box>
    </div>
  );
}
